package net.mcgassortment;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class MCGItemGroup {
    public static ItemGroup MCGASSORTMENT = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(MCGAssortment.MOD_ID, "mcgassortment"),
            FabricItemGroup.builder().displayName(Text.translatable("itemgroup.mcgassortment"))
                    .icon(() -> new ItemStack(MCGBlocks.GREEN_TERRACOTTA_STAIRS)).entries((displayContext, entries) -> {
                        entries.add(MCGBlocks.WHITE_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.WHITE_CONCRETE_SLAB);
                        entries.add(MCGBlocks.WHITE_CONCRETE_WALL);
                        entries.add(MCGBlocks.ORANGE_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.ORANGE_CONCRETE_SLAB);
                        entries.add(MCGBlocks.ORANGE_CONCRETE_WALL);
                        entries.add(MCGBlocks.MAGENTA_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.MAGENTA_CONCRETE_SLAB);
                        entries.add(MCGBlocks.MAGENTA_CONCRETE_WALL);
                        entries.add(MCGBlocks.LIGHT_BLUE_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.LIGHT_BLUE_CONCRETE_SLAB);
                        entries.add(MCGBlocks.LIGHT_BLUE_CONCRETE_WALL);
                        entries.add(MCGBlocks.YELLOW_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.YELLOW_CONCRETE_SLAB);
                        entries.add(MCGBlocks.YELLOW_CONCRETE_WALL);
                        entries.add(MCGBlocks.LIME_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.LIME_CONCRETE_SLAB);
                        entries.add(MCGBlocks.LIME_CONCRETE_WALL);
                        entries.add(MCGBlocks.PINK_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.PINK_CONCRETE_SLAB);
                        entries.add(MCGBlocks.PINK_CONCRETE_WALL);
                        entries.add(MCGBlocks.GRAY_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.GRAY_CONCRETE_SLAB);
                        entries.add(MCGBlocks.GRAY_CONCRETE_WALL);
                        entries.add(MCGBlocks.LIGHT_GRAY_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.LIGHT_GRAY_CONCRETE_SLAB);
                        entries.add(MCGBlocks.LIGHT_GRAY_CONCRETE_WALL);
                        entries.add(MCGBlocks.CYAN_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.CYAN_CONCRETE_SLAB);
                        entries.add(MCGBlocks.CYAN_CONCRETE_WALL);
                        entries.add(MCGBlocks.PURPLE_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.PURPLE_CONCRETE_SLAB);
                        entries.add(MCGBlocks.PURPLE_CONCRETE_WALL);
                        entries.add(MCGBlocks.BLUE_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.BLUE_CONCRETE_SLAB);
                        entries.add(MCGBlocks.BLUE_CONCRETE_WALL);
                        entries.add(MCGBlocks.BROWN_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.BROWN_CONCRETE_SLAB);
                        entries.add(MCGBlocks.BROWN_CONCRETE_WALL);
                        entries.add(MCGBlocks.GREEN_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.GREEN_CONCRETE_SLAB);
                        entries.add(MCGBlocks.GREEN_CONCRETE_WALL);
                        entries.add(MCGBlocks.RED_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.RED_CONCRETE_SLAB);
                        entries.add(MCGBlocks.RED_CONCRETE_WALL);
                        entries.add(MCGBlocks.BLACK_CONCRETE_STAIRS);
                        entries.add(MCGBlocks.BLACK_CONCRETE_SLAB);
                        entries.add(MCGBlocks.BLACK_CONCRETE_WALL);

                        entries.add(MCGBlocks.WHITE_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.WHITE_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.WHITE_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.ORANGE_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.ORANGE_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.ORANGE_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.MAGENTA_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.MAGENTA_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.MAGENTA_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.LIGHT_BLUE_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.LIGHT_BLUE_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.YELLOW_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.YELLOW_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.YELLOW_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.LIME_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.LIME_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.LIME_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.PINK_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.PINK_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.PINK_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.GRAY_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.GRAY_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.GRAY_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.LIGHT_GRAY_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.LIGHT_GRAY_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.CYAN_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.CYAN_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.CYAN_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.PURPLE_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.PURPLE_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.PURPLE_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.BLUE_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.BLUE_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.BLUE_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.BROWN_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.BROWN_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.BROWN_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.GREEN_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.GREEN_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.GREEN_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.RED_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.RED_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.RED_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.BLACK_TERRACOTTA_STAIRS);
                        entries.add(MCGBlocks.BLACK_TERRACOTTA_SLAB);
                        entries.add(MCGBlocks.BLACK_TERRACOTTA_WALL);
                        entries.add(MCGBlocks.BORDERLESS_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_WHITE_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_WHITE_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_ORANGE_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_ORANGE_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_MAGENTA_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_MAGENTA_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_LIGHT_BLUE_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_LIGHT_BLUE_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_YELLOW_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_YELLOW_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_LIME_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_LIME_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_PINK_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_PINK_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_GRAY_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_GRAY_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_LIGHT_GRAY_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_LIGHT_GRAY_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_CYAN_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_CYAN_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_PURPLE_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_PURPLE_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_BLUE_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_BLUE_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_BROWN_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_BROWN_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_GREEN_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_GREEN_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_RED_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_RED_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_BLACK_STAINED_GLASS);
                        entries.add(MCGBlocks.BORDERLESS_BLACK_STAINED_GLASS_PANE);
                        entries.add(MCGBlocks.BORDERLESS_TINTED_GLASS);
                        entries.add(MCGBlocks.RAW_BEEF_BLOCK);
                        entries.add(MCGBlocks.RAW_PORK_BLOCK);
                        entries.add(MCGBlocks.ROTTEN_FLESH_BLOCK);
                        entries.add(MCGBlocks.BAMBOO_THATCH);
                        entries.add(MCGBlocks.BAMBOO_THATCH_STAIRS);
                        entries.add(MCGBlocks.BAMBOO_THATCH_SLAB);
                        entries.add(MCGBlocks.BAMBOO_THATCH_RUG);
                        entries.add(MCGItems.TALLOW);
                        entries.add(MCGBlocks.CRATE);
                    }).build());
    public static void registerItemGroups() {
        MCGAssortment.LOGGER.info("Registering Item Groups for " + MCGAssortment.MOD_ID);
    }
}

