package net.mcgassortment.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.mcgassortment.MCGBlocks;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class MCGLootTableGenerator extends FabricBlockLootTableProvider {
    public MCGLootTableGenerator(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        addDrop(MCGBlocks.WHITE_CONCRETE_WALL);
        addDrop(MCGBlocks.WHITE_CONCRETE_STAIRS);
        addDrop(MCGBlocks.WHITE_CONCRETE_SLAB, slabDrops(MCGBlocks.WHITE_CONCRETE_SLAB));
        addDrop(MCGBlocks.WHITE_TERRACOTTA_WALL);
        addDrop(MCGBlocks.WHITE_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.WHITE_TERRACOTTA_SLAB, slabDrops(MCGBlocks.WHITE_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.ORANGE_CONCRETE_WALL);
        addDrop(MCGBlocks.ORANGE_CONCRETE_STAIRS);
        addDrop(MCGBlocks.ORANGE_CONCRETE_SLAB, slabDrops(MCGBlocks.ORANGE_CONCRETE_SLAB));
        addDrop(MCGBlocks.ORANGE_TERRACOTTA_WALL);
        addDrop(MCGBlocks.ORANGE_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.ORANGE_TERRACOTTA_SLAB, slabDrops(MCGBlocks.ORANGE_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.MAGENTA_CONCRETE_WALL);
        addDrop(MCGBlocks.MAGENTA_CONCRETE_STAIRS);
        addDrop(MCGBlocks.MAGENTA_CONCRETE_SLAB, slabDrops(MCGBlocks.MAGENTA_CONCRETE_SLAB));
        addDrop(MCGBlocks.MAGENTA_TERRACOTTA_WALL);
        addDrop(MCGBlocks.MAGENTA_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.MAGENTA_TERRACOTTA_SLAB, slabDrops(MCGBlocks.MAGENTA_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.LIGHT_BLUE_CONCRETE_WALL);
        addDrop(MCGBlocks.LIGHT_BLUE_CONCRETE_STAIRS);
        addDrop(MCGBlocks.LIGHT_BLUE_CONCRETE_SLAB, slabDrops(MCGBlocks.LIGHT_BLUE_CONCRETE_SLAB));
        addDrop(MCGBlocks.LIGHT_BLUE_TERRACOTTA_WALL);
        addDrop(MCGBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.LIGHT_BLUE_TERRACOTTA_SLAB, slabDrops(MCGBlocks.LIGHT_BLUE_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.YELLOW_CONCRETE_WALL);
        addDrop(MCGBlocks.YELLOW_CONCRETE_STAIRS);
        addDrop(MCGBlocks.YELLOW_CONCRETE_SLAB, slabDrops(MCGBlocks.YELLOW_CONCRETE_SLAB));
        addDrop(MCGBlocks.YELLOW_TERRACOTTA_WALL);
        addDrop(MCGBlocks.YELLOW_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.YELLOW_TERRACOTTA_SLAB, slabDrops(MCGBlocks.YELLOW_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.LIME_CONCRETE_WALL);
        addDrop(MCGBlocks.LIME_CONCRETE_STAIRS);
        addDrop(MCGBlocks.LIME_CONCRETE_SLAB, slabDrops(MCGBlocks.LIME_CONCRETE_SLAB));
        addDrop(MCGBlocks.LIME_TERRACOTTA_WALL);
        addDrop(MCGBlocks.LIME_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.LIME_TERRACOTTA_SLAB, slabDrops(MCGBlocks.LIME_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.PINK_CONCRETE_WALL);
        addDrop(MCGBlocks.PINK_CONCRETE_STAIRS);
        addDrop(MCGBlocks.PINK_CONCRETE_SLAB, slabDrops(MCGBlocks.PINK_CONCRETE_SLAB));
        addDrop(MCGBlocks.PINK_TERRACOTTA_WALL);
        addDrop(MCGBlocks.PINK_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.PINK_TERRACOTTA_SLAB, slabDrops(MCGBlocks.PINK_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.GRAY_CONCRETE_WALL);
        addDrop(MCGBlocks.GRAY_CONCRETE_STAIRS);
        addDrop(MCGBlocks.GRAY_CONCRETE_SLAB, slabDrops(MCGBlocks.GRAY_CONCRETE_SLAB));
        addDrop(MCGBlocks.GRAY_TERRACOTTA_WALL);
        addDrop(MCGBlocks.GRAY_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.GRAY_TERRACOTTA_SLAB, slabDrops(MCGBlocks.GRAY_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.LIGHT_GRAY_CONCRETE_WALL);
        addDrop(MCGBlocks.LIGHT_GRAY_CONCRETE_STAIRS);
        addDrop(MCGBlocks.LIGHT_GRAY_CONCRETE_SLAB, slabDrops(MCGBlocks.LIGHT_GRAY_CONCRETE_SLAB));
        addDrop(MCGBlocks.LIGHT_GRAY_TERRACOTTA_WALL);
        addDrop(MCGBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.LIGHT_GRAY_TERRACOTTA_SLAB, slabDrops(MCGBlocks.LIGHT_GRAY_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.CYAN_CONCRETE_WALL);
        addDrop(MCGBlocks.CYAN_CONCRETE_STAIRS);
        addDrop(MCGBlocks.CYAN_CONCRETE_SLAB, slabDrops(MCGBlocks.CYAN_CONCRETE_SLAB));
        addDrop(MCGBlocks.CYAN_TERRACOTTA_WALL);
        addDrop(MCGBlocks.CYAN_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.CYAN_TERRACOTTA_SLAB, slabDrops(MCGBlocks.CYAN_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.PURPLE_CONCRETE_WALL);
        addDrop(MCGBlocks.PURPLE_CONCRETE_STAIRS);
        addDrop(MCGBlocks.PURPLE_CONCRETE_SLAB, slabDrops(MCGBlocks.PURPLE_CONCRETE_SLAB));
        addDrop(MCGBlocks.PURPLE_TERRACOTTA_WALL);
        addDrop(MCGBlocks.PURPLE_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.PURPLE_TERRACOTTA_SLAB, slabDrops(MCGBlocks.PURPLE_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.BLUE_CONCRETE_WALL);
        addDrop(MCGBlocks.BLUE_CONCRETE_STAIRS);
        addDrop(MCGBlocks.BLUE_CONCRETE_SLAB, slabDrops(MCGBlocks.BLUE_CONCRETE_SLAB));
        addDrop(MCGBlocks.BLUE_TERRACOTTA_WALL);
        addDrop(MCGBlocks.BLUE_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.BLUE_TERRACOTTA_SLAB, slabDrops(MCGBlocks.BLUE_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.BROWN_CONCRETE_WALL);
        addDrop(MCGBlocks.BROWN_CONCRETE_STAIRS);
        addDrop(MCGBlocks.BROWN_CONCRETE_SLAB, slabDrops(MCGBlocks.BROWN_CONCRETE_SLAB));
        addDrop(MCGBlocks.BROWN_TERRACOTTA_WALL);
        addDrop(MCGBlocks.BROWN_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.BROWN_TERRACOTTA_SLAB, slabDrops(MCGBlocks.BROWN_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.GREEN_CONCRETE_WALL);
        addDrop(MCGBlocks.GREEN_CONCRETE_STAIRS);
        addDrop(MCGBlocks.GREEN_CONCRETE_SLAB, slabDrops(MCGBlocks.GREEN_CONCRETE_SLAB));
        addDrop(MCGBlocks.GREEN_TERRACOTTA_WALL);
        addDrop(MCGBlocks.GREEN_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.GREEN_TERRACOTTA_SLAB, slabDrops(MCGBlocks.GREEN_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.RED_CONCRETE_WALL);
        addDrop(MCGBlocks.RED_CONCRETE_STAIRS);
        addDrop(MCGBlocks.RED_CONCRETE_SLAB, slabDrops(MCGBlocks.RED_CONCRETE_SLAB));
        addDrop(MCGBlocks.RED_TERRACOTTA_WALL);
        addDrop(MCGBlocks.RED_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.RED_TERRACOTTA_SLAB, slabDrops(MCGBlocks.RED_TERRACOTTA_SLAB));
        addDrop(MCGBlocks.BLACK_CONCRETE_WALL);
        addDrop(MCGBlocks.BLACK_CONCRETE_STAIRS);
        addDrop(MCGBlocks.BLACK_CONCRETE_SLAB, slabDrops(MCGBlocks.BLACK_CONCRETE_SLAB));
        addDrop(MCGBlocks.BLACK_TERRACOTTA_WALL);
        addDrop(MCGBlocks.BLACK_TERRACOTTA_STAIRS);
        addDrop(MCGBlocks.BLACK_TERRACOTTA_SLAB, slabDrops(MCGBlocks.BLACK_TERRACOTTA_SLAB));

        addDropWithSilkTouch(MCGBlocks.BORDERLESS_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_WHITE_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_WHITE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_ORANGE_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_ORANGE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_MAGENTA_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_MAGENTA_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_LIGHT_BLUE_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_LIGHT_BLUE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_YELLOW_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_YELLOW_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_LIME_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_LIME_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_PINK_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_PINK_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_GRAY_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_GRAY_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_LIGHT_GRAY_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_LIGHT_GRAY_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_CYAN_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_CYAN_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_PURPLE_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_PURPLE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_BLUE_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_BLUE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_BROWN_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_BROWN_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_GREEN_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_GREEN_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_RED_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_RED_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_BLACK_STAINED_GLASS);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_BLACK_STAINED_GLASS_PANE);
        addDropWithSilkTouch(MCGBlocks.BORDERLESS_TINTED_GLASS);
        addDrop(MCGBlocks.RAW_BEEF_BLOCK);
        addDrop(MCGBlocks.RAW_PORK_BLOCK);
        addDrop(MCGBlocks.ROTTEN_FLESH_BLOCK);
        addDrop(MCGBlocks.BAMBOO_THATCH);
        addDrop(MCGBlocks.BAMBOO_THATCH_STAIRS);
        addDrop(MCGBlocks.BAMBOO_THATCH_SLAB);
        addDrop(MCGBlocks.BAMBOO_THATCH_RUG);
        addDrop(MCGBlocks.CRATE);
    }
}